//! Compile locale TOML files into perfect-hash maps.
//!
//! Cargo already skips this script when locale files are unchanged
//! (`rerun-if-changed`). We also skip rewriting `catalogs.rs` when the
//! content hash matches, so rustc does not recompile the crate on a no-op.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const LANGS: &[&str] = &["en", "de", "es", "ar", "ru", "zh", "ja"];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let locales = manifest.join("locales");
    println!("cargo:rerun-if-changed=locales");
    for lang in LANGS {
        println!("cargo:rerun-if-changed=locales/{lang}.toml");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let catalogs_path = out_dir.join("catalogs.rs");
    let hash_path = out_dir.join("catalogs.hash");

    let mut entries: Vec<(String, PathBuf, Vec<u8>)> = Vec::new();
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    use std::hash::{Hash, Hasher};
    for lang in LANGS {
        let path = locales.join(format!("{lang}.toml"));
        let bytes = fs::read(&path).unwrap_or_else(|e| {
            panic!("missing locale file {}: {e}", path.display());
        });
        path.display().to_string().hash(&mut hasher);
        bytes.hash(&mut hasher);
        entries.push(((*lang).to_string(), path, bytes));
    }
    let hash = format!("{:016x}", hasher.finish());
    if hash_path
        .exists()
        .then(|| fs::read_to_string(&hash_path).ok())
        .flatten()
        .as_deref()
        == Some(hash.as_str())
        && catalogs_path.exists()
    {
        return;
    }

    let mut generated = String::new();
    generated.push_str("// @generated by abs-i18n/build.rs — do not edit.\n");
    for (lang, path, bytes) in &entries {
        let text = std::str::from_utf8(bytes).unwrap_or_else(|_| {
            panic!("{} is not UTF-8", path.display());
        });
        let value: toml::Value = toml::from_str(text).unwrap_or_else(|e| {
            panic!("parse {}: {e}", path.display());
        });
        let mut flat = BTreeMap::new();
        flatten("", &value, &mut flat);
        let ident = lang.to_ascii_uppercase();
        generated.push_str(&format!(
            "pub static {ident}: ::phf::Map<&'static str, &'static str> = "
        ));
        let formatted_entries: Vec<(String, String)> = flat
            .iter()
            .map(|(k, v)| (k.clone(), format!("{:?}", v.as_str())))
            .collect();
        let mut map = phf_codegen::Map::new();
        for (k, v) in &formatted_entries {
            map.entry(k.as_str(), v.as_str());
        }
        generated.push_str(&map.build().to_string());
        generated.push_str(";\n\n");
    }

    let mut file = fs::File::create(&catalogs_path).expect("write catalogs.rs");
    file.write_all(generated.as_bytes())
        .expect("write catalogs.rs");
    fs::write(&hash_path, hash).expect("write catalogs.hash");
}

fn flatten(prefix: &str, value: &toml::Value, out: &mut BTreeMap<String, String>) {
    match value {
        toml::Value::Table(table) => {
            for (key, child) in table {
                let next = if prefix.is_empty() {
                    key.clone()
                } else {
                    format!("{prefix}.{key}")
                };
                flatten(&next, child, out);
            }
        }
        toml::Value::String(s) => {
            out.insert(prefix.to_string(), s.clone());
        }
        toml::Value::Integer(i) => {
            out.insert(prefix.to_string(), i.to_string());
        }
        toml::Value::Boolean(b) => {
            out.insert(prefix.to_string(), b.to_string());
        }
        toml::Value::Float(f) => {
            out.insert(prefix.to_string(), f.to_string());
        }
        other => panic!("unsupported TOML value at {prefix}: {other}"),
    }
}
