use crate::cli::Cli;
use crate::config::Config;
use crate::utils::{check_sudo_removal, run_command, sh_single_quote};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

static LIMITER_CONF_COUNTER: AtomicU64 = AtomicU64::new(0);

pub const CHROOT_PARALLEL_DROPIN: &str = "abs-parallel.conf";

/// Resolve per-package compilation thread count (never reduced by the scheduler).
pub fn resolve_package_threads(pkg_name: &str, config: &Config, cli: &Cli) -> Option<usize> {
    if let Some(pkg) = config.packages.get(pkg_name)
        && let Some(n) = pkg.compilation_threads
    {
        return Some(n);
    }
    if let Some(n) = cli.jobs {
        return Some(n);
    }
    config.build.default_compilation_threads
}

/// `export` lines limiting every common parallel build tool to `threads` jobs.
fn limiter_exports(threads: usize) -> String {
    format!(
        "export MAKEFLAGS=\"-j{threads}\"\n\
export NPROC={threads}\n\
export CMAKE_BUILD_PARALLEL_LEVEL={threads}\n\
export NINJAFLAGS=\"-j{threads}\"\n\
export CARGO_BUILD_JOBS={threads}\n\
export MAX_JOBS={threads}\n"
    )
}

/// makepkg.conf.d drop-in content for chroot builds. makepkg sources `makepkg.conf.d/*.conf`
/// after the main makepkg.conf, so these exports win over distro defaults and over the
/// values makechrootpkg appends to the copy's makepkg.conf.
pub fn parallel_limiter_conf(threads: usize) -> String {
    format!(
        "# Generated by ABS — parallel compilation limiters\n{}",
        limiter_exports(threads)
    )
}

/// Wrapper makepkg.conf for local / PGO builds, passed to makepkg via `MAKEPKG_CONF=<file>`.
///
/// A plain env prefix is not enough: makepkg sources the system makepkg.conf after reading
/// the environment and only preserves a whitelist of variables (PKGDEST, SRCDEST, ...), so
/// env MAKEFLAGS / NINJAFLAGS are clobbered whenever the distro conf sets them (CachyOS
/// does). This wrapper replays the normal config chain — system conf, its `.d` drop-ins,
/// then the user conf — and applies the limiter exports last so they always win.
pub fn local_limiter_conf(threads: usize) -> String {
    let base =
        std::env::var("MAKEPKG_CONF").unwrap_or_else(|_| "/etc/makepkg.conf".to_string());
    let mut conf = format!(
        "# Generated by ABS — parallel compilation limiters\n\
_abs_base={}\n\
[[ -r \"$_abs_base\" ]] && source \"$_abs_base\"\n\
if [[ -d \"$_abs_base.d\" ]]; then\n\
    for _abs_dropin in \"$_abs_base.d\"/*.conf; do\n\
        [[ -r \"$_abs_dropin\" ]] && source \"$_abs_dropin\"\n\
    done\n\
fi\n",
        sh_single_quote(&base)
    );
    // makepkg only sources the user conf when running with the default system conf.
    if base == "/etc/makepkg.conf" {
        conf.push_str(
            "_abs_user=\"${XDG_CONFIG_HOME:-$HOME/.config}/pacman/makepkg.conf\"\n\
if [[ -r \"$_abs_user\" ]]; then\n\
    source \"$_abs_user\"\n\
elif [[ -r \"$HOME/.makepkg.conf\" ]]; then\n\
    source \"$HOME/.makepkg.conf\"\n\
fi\n",
        );
    }
    conf.push_str("unset _abs_base _abs_user _abs_dropin\n");
    conf.push_str(&limiter_exports(threads));
    conf
}

/// Temp wrapper conf on disk; removed when dropped (i.e. after the build command ran).
pub struct LocalLimiterGuard {
    path: PathBuf,
}

impl LocalLimiterGuard {
    /// `MAKEPKG_CONF='<path>'` env assignment for a makepkg command line.
    pub fn env_assignment(&self) -> String {
        format!("MAKEPKG_CONF={}", sh_single_quote(&self.path.to_string_lossy()))
    }
}

impl Drop for LocalLimiterGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.path);
    }
}

/// Write the wrapper conf for `pkg` into the temp dir.
pub fn write_local_limiter_conf(pkg: &str, threads: usize) -> Result<LocalLimiterGuard, String> {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let safe_pkg: String = pkg
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' { ch } else { '_' })
        .collect();
    let contents = local_limiter_conf(threads);

    for _ in 0..16 {
        let counter = LIMITER_CONF_COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "abs_makepkg_{safe_pkg}_{}_{}_{}.conf",
            std::process::id(),
            stamp,
            counter
        ));
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        match options.open(&path) {
            Ok(mut file) => {
                file.write_all(contents.as_bytes())
                    .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;
                return Ok(LocalLimiterGuard { path });
            }
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(e) => return Err(format!("Failed to create {}: {e}", path.display())),
        }
    }

    Err("Failed to create a unique temporary makepkg configuration file".into())
}

/// Write or remove `<chrootdir>/<copy>/etc/makepkg.conf.d/abs-parallel.conf`.
pub fn apply_chroot_parallel_dropin(
    chrootdir: &Path,
    copy_name: &str,
    threads: Option<usize>,
) -> Result<(), String> {
    let conf_d = chrootdir
        .join(copy_name)
        .join("etc")
        .join("makepkg.conf.d");
    let dropin = conf_d.join(CHROOT_PARALLEL_DROPIN);

    match threads {
        None => {
            if dropin.exists() {
                check_sudo_removal(&dropin)?;
            }
            Ok(())
        }
        Some(n) => {
            let content = parallel_limiter_conf(n);
            run_command(
                "sudo",
                &["mkdir", "-p", conf_d.to_string_lossy().as_ref()],
                None::<&str>,
            )?;
            let script = format!(
                "printf %s {} | sudo tee {} > /dev/null",
                sh_single_quote(&content),
                sh_single_quote(&dropin.to_string_lossy()),
            );
            run_command("sh", &["-c", &script], None::<&str>)?;
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parallel_limiter_conf_content() {
        let conf = parallel_limiter_conf(8);
        assert!(conf.contains("export MAKEFLAGS=\"-j8\""));
        assert!(conf.contains("export NPROC=8"));
        assert!(conf.contains("export CMAKE_BUILD_PARALLEL_LEVEL=8"));
        assert!(conf.contains("export NINJAFLAGS=\"-j8\""));
        assert!(conf.contains("export CARGO_BUILD_JOBS=8"));
        assert!(conf.contains("export MAX_JOBS=8"));
    }

    #[test]
    fn local_limiter_conf_sources_system_chain_then_overrides() {
        let conf = local_limiter_conf(6);
        let source_pos = conf.find("source \"$_abs_base\"").unwrap();
        let dropin_pos = conf.find("\"$_abs_base.d\"/*.conf").unwrap();
        let export_pos = conf.find("export MAKEFLAGS=\"-j6\"").unwrap();
        assert!(source_pos < dropin_pos);
        assert!(dropin_pos < export_pos);
        assert!(conf.contains("export CARGO_BUILD_JOBS=6"));
    }

    #[test]
    fn local_limiter_guard_writes_and_removes_file() {
        let guard = write_local_limiter_conf("testpkg", 4).unwrap();
        let assignment = guard.env_assignment();
        assert!(assignment.starts_with("MAKEPKG_CONF='"));
        let path = std::path::PathBuf::from(
            assignment
                .trim_start_matches("MAKEPKG_CONF='")
                .trim_end_matches('\''),
        );
        assert!(path.exists());
        drop(guard);
        assert!(!path.exists());
    }
}
